name: py310
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.18
  - pip=25.1
  - numpy=1.26.4
  - pillow=11.1.0
  - pip:
    - opencv-python==4.10.0.84
    - torch==2.5.1
    - torchvision==0.20.1
    - ultralytics==8.3.154
    - python-osc==1.9.3
    - requests==2.32.4
    - tqdm==4.67.1
    - matplotlib==3.10.0
    - pyyaml==6.0.2
